services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: all
               capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      # This tells Open WebUI to look for the Ollama instance on the local network inside Docker
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open_webui_data:/app/data
    depends_on:
      - ollama

volumes:
  ollama_data:
    driver: local
  open_webui_data:
    driver: local
